scanner:
    linter: flake8  # Other option is pycodestyle

no_blank_comment: False  # If True, no comment is made on PR without any errors.
descending_issues_order: True  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file

[flake8]
exclude =
    .git,
    __pycache__,
    build,
    dist

max-line-length = 100

ignore =
    # too many leading '#' for block comment
    E266,
    # do not assign a lambda expression, use a def
    E731,
    # whitespace before ':'
    E203,
    # multiple spaces before operator
    E221,
    # line break before binary operator
    W503,
    # imported but unused
    F401,
    # module level import not at top of file
    E402,

per-file-ignores =
    scripts/timew-status-indicator.py:E226,W292
