prog_name: repolite
top_dir: docs  # local directory path for enabled repositories
pull_with_rebase: false  # use --ff-only if false
# add new repo_name sections as needed
repos:
  - repo_name: timew-addons-sum
    repo_alias: sum
    repo_url: git@github.com:sarnold/timew-addons-sum.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: draft-v0
    repo_hash: null
    repo_create_tag_msg: tag for RC release
    repo_create_tag_annotated: true
    repo_create_tag_signed: false
    repo_push_new_tags: false
    repo_signing_key: null
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
