name: Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Deps for system pkgs
        run: |
          sudo apt-get -qq update
          sudo apt-get install -yqq python3-gi python3-gi-cairo gir1.2-gtk-3.0
          sudo apt-get install -yqq libgirepository1.0-dev libappindicator3-dev
          sudo apt-get install -yqq software-properties-common libgirepository-2.0-dev
          sudo add-apt-repository -y -s ppa:nerdboy/embedded
          sudo apt-get -qq update
          sudo apt-get install -yqq timew-report

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: pre-commit/action@v3.0.1
        id: precommit

      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@d4e381c660200e0fbca0b897f6192ad391ee10c5
        with:
          name: pre-commit
